features:
  extractor_name: 'SIFT'
  max_keypoints: 2048
  # descriptor_dim: 256
  nms_radius: -1
  # keypoint_threshold: 0.005
  # remove_borders: 4
matching:
  matching_name: 'SuperGlue'
  weights: 'outdoor'
  # descriptor_dim: 256
  # keypoint_encoder: [32, 64, 128, 256]
  # GNN_layers: ['self', 'cross']*9
  # sinkhorn_iterations: 20
  # match_threshold: 0.2